import type { Metadata } from "next";
import localFont from "next/font/local";

import MainLayout from "@/components/layouts/MainLayout";
import { ThemeProvider } from "@/components/provider/theme-provider";

import "./globals.css";

const kiwiMaruLight = localFont({
  src: "./fonts/KiwiMaru-Light.ttf",
  variable: "--font-kiwimaru-Light",
  weight: "300",
});

const kiwiMaruMedium = localFont({
  src: "./fonts/KiwiMaru-Medium.ttf",
  variable: "--font-kiwimaru-medium",
  weight: "400",
});

const kiwiMaruRegular = localFont({
  src: "./fonts/KiwiMaru-Regular.ttf",
  variable: "--font-kiwimaru-regular",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${kiwiMaruRegular.className} ${kiwiMaruLight.variable} ${kiwiMaruMedium.variable} ${kiwiMaruRegular.variable}`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MainLayout>{children}</MainLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
